app:
    resource: "@AppBundle/Controller/"
    type: annotation

api:
    resource: "@AppBundle/Api/"
    type: annotation
    prefix: /api

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc